[versions]
viaversion = "5.3.1"
netty = "4.1.115.Final"

[libraries.viaversion-api]
group = "com.viaversion"
name = "viaversion-api"
version.ref = "viaversion"

[libraries.viaversion-bukkit]
group = "com.viaversion"
name = "viaversion-bukkit"
version.ref = "viaversion"

[libraries.viabackwards]
group = "com.viaversion"
name = "viabackwards"
version.ref = "viaversion"

[libraries.netty-codec-http]
group = "io.netty"
name = "netty-codec-http"
version.ref = "netty"